// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(SilentSignalsDbContext))]
    [Migration("20260112143738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Domain.Entities.ConversionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConversionHistories");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyAR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.MorseMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Char")
                        .IsUnique();

                    b.ToTable("MorseMappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Char = "A",
                            Pattern = ".-"
                        },
                        new
                        {
                            Id = 2,
                            Char = "B",
                            Pattern = "-..."
                        },
                        new
                        {
                            Id = 3,
                            Char = "C",
                            Pattern = "-.-."
                        },
                        new
                        {
                            Id = 4,
                            Char = "D",
                            Pattern = "-.."
                        },
                        new
                        {
                            Id = 5,
                            Char = "E",
                            Pattern = "."
                        },
                        new
                        {
                            Id = 6,
                            Char = "F",
                            Pattern = "..-."
                        },
                        new
                        {
                            Id = 7,
                            Char = "G",
                            Pattern = "--."
                        },
                        new
                        {
                            Id = 8,
                            Char = "H",
                            Pattern = "...."
                        },
                        new
                        {
                            Id = 9,
                            Char = "I",
                            Pattern = ".."
                        },
                        new
                        {
                            Id = 10,
                            Char = "J",
                            Pattern = ".---"
                        },
                        new
                        {
                            Id = 11,
                            Char = "K",
                            Pattern = "-.-"
                        },
                        new
                        {
                            Id = 12,
                            Char = "L",
                            Pattern = ".-.."
                        },
                        new
                        {
                            Id = 13,
                            Char = "M",
                            Pattern = "--"
                        },
                        new
                        {
                            Id = 14,
                            Char = "N",
                            Pattern = "-."
                        },
                        new
                        {
                            Id = 15,
                            Char = "O",
                            Pattern = "---"
                        },
                        new
                        {
                            Id = 16,
                            Char = "P",
                            Pattern = ".--."
                        },
                        new
                        {
                            Id = 17,
                            Char = "Q",
                            Pattern = "--.-"
                        },
                        new
                        {
                            Id = 18,
                            Char = "R",
                            Pattern = ".-."
                        },
                        new
                        {
                            Id = 19,
                            Char = "S",
                            Pattern = "..."
                        },
                        new
                        {
                            Id = 20,
                            Char = "T",
                            Pattern = "-"
                        },
                        new
                        {
                            Id = 21,
                            Char = "U",
                            Pattern = "..-"
                        },
                        new
                        {
                            Id = 22,
                            Char = "V",
                            Pattern = "...-"
                        },
                        new
                        {
                            Id = 23,
                            Char = "W",
                            Pattern = ".--"
                        },
                        new
                        {
                            Id = 24,
                            Char = "X",
                            Pattern = "-..-"
                        },
                        new
                        {
                            Id = 25,
                            Char = "Y",
                            Pattern = "-.--"
                        },
                        new
                        {
                            Id = 26,
                            Char = "Z",
                            Pattern = "--.."
                        },
                        new
                        {
                            Id = 27,
                            Char = "0",
                            Pattern = "-----"
                        },
                        new
                        {
                            Id = 28,
                            Char = "1",
                            Pattern = ".----"
                        },
                        new
                        {
                            Id = 29,
                            Char = "2",
                            Pattern = "..---"
                        },
                        new
                        {
                            Id = 30,
                            Char = "3",
                            Pattern = "...--"
                        },
                        new
                        {
                            Id = 31,
                            Char = "4",
                            Pattern = "....-"
                        },
                        new
                        {
                            Id = 32,
                            Char = "5",
                            Pattern = "....."
                        },
                        new
                        {
                            Id = 33,
                            Char = "6",
                            Pattern = "-...."
                        },
                        new
                        {
                            Id = 34,
                            Char = "7",
                            Pattern = "--..."
                        },
                        new
                        {
                            Id = 35,
                            Char = "8",
                            Pattern = "---.."
                        },
                        new
                        {
                            Id = 36,
                            Char = "9",
                            Pattern = "----."
                        });
                });

            modelBuilder.Entity("Domain.Entities.SignGesture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionAR")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SignGestures");
                });
#pragma warning restore 612, 618
        }
    }
}
