// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(SilentSignalsDbContext))]
    [Migration("20260112161926_AddIdentityAuth_v2")]
    partial class AddIdentityAuth_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ConversionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConversionHistories");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyAR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.MorseMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Char")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Char")
                        .IsUnique();

                    b.ToTable("MorseMappings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Char = "A",
                            Pattern = ".-"
                        },
                        new
                        {
                            Id = 2,
                            Char = "B",
                            Pattern = "-..."
                        },
                        new
                        {
                            Id = 3,
                            Char = "C",
                            Pattern = "-.-."
                        },
                        new
                        {
                            Id = 4,
                            Char = "D",
                            Pattern = "-.."
                        },
                        new
                        {
                            Id = 5,
                            Char = "E",
                            Pattern = "."
                        },
                        new
                        {
                            Id = 6,
                            Char = "F",
                            Pattern = "..-."
                        },
                        new
                        {
                            Id = 7,
                            Char = "G",
                            Pattern = "--."
                        },
                        new
                        {
                            Id = 8,
                            Char = "H",
                            Pattern = "...."
                        },
                        new
                        {
                            Id = 9,
                            Char = "I",
                            Pattern = ".."
                        },
                        new
                        {
                            Id = 10,
                            Char = "J",
                            Pattern = ".---"
                        },
                        new
                        {
                            Id = 11,
                            Char = "K",
                            Pattern = "-.-"
                        },
                        new
                        {
                            Id = 12,
                            Char = "L",
                            Pattern = ".-.."
                        },
                        new
                        {
                            Id = 13,
                            Char = "M",
                            Pattern = "--"
                        },
                        new
                        {
                            Id = 14,
                            Char = "N",
                            Pattern = "-."
                        },
                        new
                        {
                            Id = 15,
                            Char = "O",
                            Pattern = "---"
                        },
                        new
                        {
                            Id = 16,
                            Char = "P",
                            Pattern = ".--."
                        },
                        new
                        {
                            Id = 17,
                            Char = "Q",
                            Pattern = "--.-"
                        },
                        new
                        {
                            Id = 18,
                            Char = "R",
                            Pattern = ".-."
                        },
                        new
                        {
                            Id = 19,
                            Char = "S",
                            Pattern = "..."
                        },
                        new
                        {
                            Id = 20,
                            Char = "T",
                            Pattern = "-"
                        },
                        new
                        {
                            Id = 21,
                            Char = "U",
                            Pattern = "..-"
                        },
                        new
                        {
                            Id = 22,
                            Char = "V",
                            Pattern = "...-"
                        },
                        new
                        {
                            Id = 23,
                            Char = "W",
                            Pattern = ".--"
                        },
                        new
                        {
                            Id = 24,
                            Char = "X",
                            Pattern = "-..-"
                        },
                        new
                        {
                            Id = 25,
                            Char = "Y",
                            Pattern = "-.--"
                        },
                        new
                        {
                            Id = 26,
                            Char = "Z",
                            Pattern = "--.."
                        },
                        new
                        {
                            Id = 27,
                            Char = "0",
                            Pattern = "-----"
                        },
                        new
                        {
                            Id = 28,
                            Char = "1",
                            Pattern = ".----"
                        },
                        new
                        {
                            Id = 29,
                            Char = "2",
                            Pattern = "..---"
                        },
                        new
                        {
                            Id = 30,
                            Char = "3",
                            Pattern = "...--"
                        },
                        new
                        {
                            Id = 31,
                            Char = "4",
                            Pattern = "....-"
                        },
                        new
                        {
                            Id = 32,
                            Char = "5",
                            Pattern = "....."
                        },
                        new
                        {
                            Id = 33,
                            Char = "6",
                            Pattern = "-...."
                        },
                        new
                        {
                            Id = 34,
                            Char = "7",
                            Pattern = "--..."
                        },
                        new
                        {
                            Id = 35,
                            Char = "8",
                            Pattern = "---.."
                        },
                        new
                        {
                            Id = 36,
                            Char = "9",
                            Pattern = "----."
                        });
                });

            modelBuilder.Entity("Domain.Entities.SignGesture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionAR")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenType", "Token")
                        .IsUnique();

                    b.ToTable("SignGestures");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DescriptionAR = "إشارة الحرف A",
                            DescriptionEN = "Sign for letter A",
                            ImageUrl = "signs/A.svg",
                            Token = "A",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 102,
                            DescriptionAR = "إشارة الحرف B",
                            DescriptionEN = "Sign for letter B",
                            ImageUrl = "signs/B.svg",
                            Token = "B",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 103,
                            DescriptionAR = "إشارة الحرف C",
                            DescriptionEN = "Sign for letter C",
                            ImageUrl = "signs/C.svg",
                            Token = "C",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 104,
                            DescriptionAR = "إشارة الحرف D",
                            DescriptionEN = "Sign for letter D",
                            ImageUrl = "signs/D.svg",
                            Token = "D",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 105,
                            DescriptionAR = "إشارة الحرف E",
                            DescriptionEN = "Sign for letter E",
                            ImageUrl = "signs/E.svg",
                            Token = "E",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 106,
                            DescriptionAR = "إشارة الحرف F",
                            DescriptionEN = "Sign for letter F",
                            ImageUrl = "signs/F.svg",
                            Token = "F",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 107,
                            DescriptionAR = "إشارة الحرف G",
                            DescriptionEN = "Sign for letter G",
                            ImageUrl = "signs/G.svg",
                            Token = "G",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 108,
                            DescriptionAR = "إشارة الحرف H",
                            DescriptionEN = "Sign for letter H",
                            ImageUrl = "signs/H.svg",
                            Token = "H",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 109,
                            DescriptionAR = "إشارة الحرف I",
                            DescriptionEN = "Sign for letter I",
                            ImageUrl = "signs/I.svg",
                            Token = "I",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 110,
                            DescriptionAR = "إشارة الحرف J",
                            DescriptionEN = "Sign for letter J",
                            ImageUrl = "signs/J.svg",
                            Token = "J",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 111,
                            DescriptionAR = "إشارة الحرف K",
                            DescriptionEN = "Sign for letter K",
                            ImageUrl = "signs/K.svg",
                            Token = "K",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 112,
                            DescriptionAR = "إشارة الحرف L",
                            DescriptionEN = "Sign for letter L",
                            ImageUrl = "signs/L.svg",
                            Token = "L",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 113,
                            DescriptionAR = "إشارة الحرف M",
                            DescriptionEN = "Sign for letter M",
                            ImageUrl = "signs/M.svg",
                            Token = "M",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 114,
                            DescriptionAR = "إشارة الحرف N",
                            DescriptionEN = "Sign for letter N",
                            ImageUrl = "signs/N.svg",
                            Token = "N",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 115,
                            DescriptionAR = "إشارة الحرف O",
                            DescriptionEN = "Sign for letter O",
                            ImageUrl = "signs/O.svg",
                            Token = "O",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 116,
                            DescriptionAR = "إشارة الحرف P",
                            DescriptionEN = "Sign for letter P",
                            ImageUrl = "signs/P.svg",
                            Token = "P",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 117,
                            DescriptionAR = "إشارة الحرف Q",
                            DescriptionEN = "Sign for letter Q",
                            ImageUrl = "signs/Q.svg",
                            Token = "Q",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 118,
                            DescriptionAR = "إشارة الحرف R",
                            DescriptionEN = "Sign for letter R",
                            ImageUrl = "signs/R.svg",
                            Token = "R",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 119,
                            DescriptionAR = "إشارة الحرف S",
                            DescriptionEN = "Sign for letter S",
                            ImageUrl = "signs/S.svg",
                            Token = "S",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 120,
                            DescriptionAR = "إشارة الحرف T",
                            DescriptionEN = "Sign for letter T",
                            ImageUrl = "signs/T.svg",
                            Token = "T",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 121,
                            DescriptionAR = "إشارة الحرف U",
                            DescriptionEN = "Sign for letter U",
                            ImageUrl = "signs/U.svg",
                            Token = "U",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 122,
                            DescriptionAR = "إشارة الحرف V",
                            DescriptionEN = "Sign for letter V",
                            ImageUrl = "signs/V.svg",
                            Token = "V",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 123,
                            DescriptionAR = "إشارة الحرف W",
                            DescriptionEN = "Sign for letter W",
                            ImageUrl = "signs/W.svg",
                            Token = "W",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 124,
                            DescriptionAR = "إشارة الحرف X",
                            DescriptionEN = "Sign for letter X",
                            ImageUrl = "signs/X.svg",
                            Token = "X",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 125,
                            DescriptionAR = "إشارة الحرف Y",
                            DescriptionEN = "Sign for letter Y",
                            ImageUrl = "signs/Y.svg",
                            Token = "Y",
                            TokenType = "Letter"
                        },
                        new
                        {
                            Id = 126,
                            DescriptionAR = "إشارة الحرف Z",
                            DescriptionEN = "Sign for letter Z",
                            ImageUrl = "signs/Z.svg",
                            Token = "Z",
                            TokenType = "Letter"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
